/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TestEditorRouteImport } from './routes/test-editor'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PagesRouteImport } from './routes/pages'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ConfirmEmailChangeRouteImport } from './routes/confirm-email-change'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksFilterRouteImport } from './routes/tasks.$filter'
import { Route as PagesIdRouteImport } from './routes/pages.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TestEditorRoute = TestEditorRouteImport.update({
  id: '/test-editor',
  path: '/test-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesRoute = PagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmEmailChangeRoute = ConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksFilterRoute = TasksFilterRouteImport.update({
  id: '/$filter',
  path: '/$filter',
  getParentRoute: () => TasksRoute,
} as any)
const PagesIdRoute = PagesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/pages': typeof PagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tasks': typeof TasksRouteWithChildren
  '/test-editor': typeof TestEditorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/pages/$id': typeof PagesIdRoute
  '/tasks/$filter': typeof TasksFilterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/pages': typeof PagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tasks': typeof TasksRouteWithChildren
  '/test-editor': typeof TestEditorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/pages/$id': typeof PagesIdRoute
  '/tasks/$filter': typeof TasksFilterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirm-email-change': typeof ConfirmEmailChangeRoute
  '/graph': typeof GraphRoute
  '/inbox': typeof InboxRoute
  '/pages': typeof PagesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/tasks': typeof TasksRouteWithChildren
  '/test-editor': typeof TestEditorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/pages/$id': typeof PagesIdRoute
  '/tasks/$filter': typeof TasksFilterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirm-email-change'
    | '/graph'
    | '/inbox'
    | '/pages'
    | '/reset-password'
    | '/tasks'
    | '/test-editor'
    | '/verify-email'
    | '/pages/$id'
    | '/tasks/$filter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirm-email-change'
    | '/graph'
    | '/inbox'
    | '/pages'
    | '/reset-password'
    | '/tasks'
    | '/test-editor'
    | '/verify-email'
    | '/pages/$id'
    | '/tasks/$filter'
  id:
    | '__root__'
    | '/'
    | '/confirm-email-change'
    | '/graph'
    | '/inbox'
    | '/pages'
    | '/reset-password'
    | '/tasks'
    | '/test-editor'
    | '/verify-email'
    | '/pages/$id'
    | '/tasks/$filter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmEmailChangeRoute: typeof ConfirmEmailChangeRoute
  GraphRoute: typeof GraphRoute
  InboxRoute: typeof InboxRoute
  PagesRoute: typeof PagesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  TasksRoute: typeof TasksRouteWithChildren
  TestEditorRoute: typeof TestEditorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-editor': {
      id: '/test-editor'
      path: '/test-editor'
      fullPath: '/test-editor'
      preLoaderRoute: typeof TestEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages': {
      id: '/pages'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm-email-change': {
      id: '/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/confirm-email-change'
      preLoaderRoute: typeof ConfirmEmailChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$filter': {
      id: '/tasks/$filter'
      path: '/$filter'
      fullPath: '/tasks/$filter'
      preLoaderRoute: typeof TasksFilterRouteImport
      parentRoute: typeof TasksRoute
    }
    '/pages/$id': {
      id: '/pages/$id'
      path: '/$id'
      fullPath: '/pages/$id'
      preLoaderRoute: typeof PagesIdRouteImport
      parentRoute: typeof PagesRoute
    }
  }
}

interface PagesRouteChildren {
  PagesIdRoute: typeof PagesIdRoute
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesIdRoute: PagesIdRoute,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

interface TasksRouteChildren {
  TasksFilterRoute: typeof TasksFilterRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksFilterRoute: TasksFilterRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmEmailChangeRoute: ConfirmEmailChangeRoute,
  GraphRoute: GraphRoute,
  InboxRoute: InboxRoute,
  PagesRoute: PagesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  TasksRoute: TasksRouteWithChildren,
  TestEditorRoute: TestEditorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
